### ISSUE TITLE
todo mission 답쓰기

### ISSUE THREAD

**Issue by eungyolee** [ckstmznf/SSF-2022-X-EDCAN#1]
https://marked-fern-cd3.notion.site/SSF-2022-EDCAN-todo-mission-8c889f9c04134dffbbbc829d80e78156

**Comment by kichan05** [comment]
아주 좋아요

**Comment by eungyolee** [comment]
> 아주 좋아요

이걸 다시 여시네

**Comment by kichan05** [comment]
다시 닫음
